---
- name: Install tree package on Ubuntu 20.04
  hosts: reposervers
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install tree package
      ansible.builtin.apt:
        name: tree
        state: present
